### ISSUE TITLE
Scripts do not work on kernel 4.3.x

### ISSUE THREAD

**Issue by FazleArefin** [admiralakber/thinkpad-yoga-scripts#19]
The scripts worked fine on my Yoga S1 as long as I was on kernel 4.2.x (Fedora 23). As soon as I upgraded to kernel 4.3.x all your systemd scripts stopped working. Has anyone tried the scripts on kernel 4.3.x or 4.4.x?

**Comment by eages** [comment]
Hi, I think this is a problem upstream. Check out these tickets: 
https://bugzilla.kernel.org/show_bug.cgi?id=109501
https://bugzilla.kernel.org/show_bug.cgi?id=111321

If you're experiencing the same bug as me, rotation should work after a suspend attempt.
