### ISSUE TITLE
/usr/bin/bash on Debian sid

### ISSUE THREAD

**Issue by obino** [admiralakber/thinkpad-yoga-scripts#4]
Thanks for the scripts! I am having issues using the systemd configuration file on my Debian Sid laptop, since /usr/bin/bash does not exists: if I change it to be /bin/bash it works.

**Comment by iRet** [comment]
Hi guys!
I've seen same issue on Ubuntu 15.04 with systemd.
But in my case it won't work even after fixing path.
It complains on rotate python script line:

``` python
devices = check_output(['xinput', '--list', '--name-only'],env=env).splitlines()
```

That call return non zero status. However same command works well in shell.
I feel like it runs it before X start, but only an assumption.

@obino /usr/bin/bash path is correct for Arch, so we can't just replace it.

**Comment by admiralakber** [comment]
Hi iRet, 

Do an `echo $DISPLAY` and `echo $XAUTHORITY` from  your user account and see if it makes sense with the Environment variables defined in the yoga-rotate systemd script. 

It may be worthwhile making a new issue for this to share your results.

**Comment by iRet** [comment]
@admiralakber Hi,
Unfotunately I have no more Ubuntu on my machine, switched to Arch and happy.
But as I said scripts itself working fine, problem in runners (systemd) scripts for some reason.
Also path to copy service scripts different in Ubuntu.
I mean when I started scripts (not services) maually in terminal from already started X session, all works just fine.
As well as `xinput --list --name-only` which returns a few lines ans seems working.

**Comment by iRet** [comment]
@obino sorry I was wrong, it seems, like /bin/bash exists in Arch as well :+1:
