### ISSUE TITLE
Wacon not rotating in Manjaro XFCE 0.8.12

### ISSUE THREAD

**Issue by iRet** [admiralakber/thinkpad-yoga-scripts#6]
Hi there!
I faced an issue in portrait mode display rotainting well but wacom input remains in landscape mode.
Installed from AUR: thinkpad-yoga-scripts-git version: r43.c72a475-1
btw, thanks for a great work!

**Comment by admiralakber** [comment]
Hey there, 

By default, the scripts assume your DE handles the rotation, don't worry it's easy to reconfigure.

As described in the README, you edit the configuration in the rotate script. 

`sudo(or su -c) nano <path>/rotate/thinkpad-rotate.py`

Within "CONFIGURABLES", change `rotate_pens = True`. I believe it's on line 20. Save and restart the systemd service and see how that goes.

Cheers

**Comment by iRet** [comment]
@admiralakber oh, sorry, I missed this line of README, you're right, just changed and all working fine!
Thanks!
