### ISSUE TITLE
manual installation on Ubuntu 15.04: /usr/lib/systemd/system/ doesn't exist -- add note to installation guide

### ISSUE THREAD

**Issue by sjjh** [admiralakber/thinkpad-yoga-scripts#7]
I recently got a Lenovo Yoga 12 and would like to use your scripts to be able to use it as a tablet. I tired to follow the manual installation, but unfortunately it failed as the path /usr/lib/systemd/system/ does not exist.

$ ls /usr/lib/systemd/
catalog  network  ntp-units.d  user  user-generators

It seems that for Ubuntu 15.04 this directory does not exist although Ubuntu did switch to systemd. As far as I understood by searching on the net, I can simply create the folder. I thus suggest to add a note in the installation manual that the folder might need to be created.

**Comment by admiralakber** [comment]
I'm not quite familiar with Ubuntu 15.04, but it does appear it won't do any harm. It might not be the most elegant solution. Either way, I've added a note to the README for now.

Cheers
